name: Publish Release

on:
  release:
    types:
      - published

jobs:
  python-build:
    uses: finleyfamily/workflows/.github/workflows/python.build.yml@master
    with:
      poetry-plugins: poetry-dynamic-versioning[plugin]
  publish-pypi:
    name: ⤴️ Publish 📦 To PyPI
    needs:
      - python-build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/${{ github.event.repository.name }}
    permissions:
      id-token: write
    steps:
      - name: ⤵️ Download Distribution Artifact
        uses: actions/download-artifact@v4
        with:
          name: pypi-dist
          path: dist
      - name: ⤴️ Publish 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@v1.10.1
